### ISSUE TITLE
Plugin is not working with Yarn 4.1.0

### ISSUE THREAD

**Issue by adelinmaubray** [Venryx/yarn-vtools#2]
Hi there,

I was used to use Yarn 3.2.1 with yarn-vtools to override some dependencies depending on the environnement.
Since Yarn 4.1.0, the plugin is not working anymore, with the following error

```
YN0000: · Yarn 4.1.0
Yarn-vtools-plugin starting. Config found at: /home/ubuntu/Projects/DGEAC/app-forms-multi-repo/vinhdicator/vinhdicator/yarn-vtools-install-plugin.config.js
➤ YN0000: ┌ Resolution step
➤ YN0001: │ TypeError: Cannot destructure property 'packageExtensions' of 'undefined' as it is undefined.                                                                                                
    at rA.normalizePackage (/home/ubuntu/Projects/DGEAC/app-forms-multi-repo/vinhdicator/vinhdicator/.yarn/releases/yarn-4.1.0.cjs:149:2093)
    at configuration.normalizePackage (/home/ubuntu/Projects/DGEAC/app-forms-multi-repo/vinhdicator/vinhdicator/.yarn/plugins/yarn-vtools-plugin/index.js:143:66)
    at Pt.preparePackage (/home/ubuntu/Projects/DGEAC/app-forms-multi-repo/vinhdicator/vinhdicator/.yarn/releases/yarn-4.1.0.cjs:210:5882)
    at async ne (/home/ubuntu/Projects/DGEAC/app-forms-multi-repo/vinhdicator/vinhdicator/.yarn/releases/yarn-4.1.0.cjs:210:7583)
    at async Promise.allSettled (index 0)
    at async Uc (/home/ubuntu/Projects/DGEAC/app-forms-multi-repo/vinhdicator/vinhdicator/.yarn/releases/yarn-4.1.0.cjs:140:53244)
    at async /home/ubuntu/Projects/DGEAC/app-forms-multi-repo/vinhdicator/vinhdicator/.yarn/releases/yarn-4.1.0.cjs:210:9140
    at async Nt.startProgressPromise (/home/ubuntu/Projects/DGEAC/app-forms-multi-repo/vinhdicator/vinhdicator/.yarn/releases/yarn-4.1.0.cjs:140:137284)
    at async Pt.resolveEverything (/home/ubuntu/Projects/DGEAC/app-forms-multi-repo/vinhdicator/vinhdicator/.yarn/releases/yarn-4.1.0.cjs:210:7138)
    at async /home/ubuntu/Projects/DGEAC/app-forms-multi-repo/vinhdicator/vinhdicator/.yarn/releases/yarn-4.1.0.cjs:213:2648
```

What can be done to fix this?
Thanks a lot

**Comment by Venryx** [comment]
Sorry, but I haven't used this plugin in a long time, and don't have the time/motivation to debug the issue.

If you or someone else ends up finding a fix though, I'd be willing to merge it.
